version: '3.1'
services:
  guardian_authentication:
    build:
      context: .
    image: 'guardian_authentication:0.0.1'
    ports:
      - '8000:8000'
    environment:
      - MIX_ENV=prod # precisa?
      - PORT=8000 # precisa?

