version: '3.1'

services:
  db:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: authentication
      POSTGRES_PASSWORD: authentication
      POSTGRES_DB: authentication_dev
      